# name: zshrc stub
#
# ~/.zshrc used to be a symlink into this repo, and that was the single biggest
# source of a dirty checkout. Installers append to it — Coder does on every
# workspace create, oh-my-zsh and p10k want to, bun does it unconditionally —
# and every one of those appends was a commit waiting to happen.
#
# So ~/.zshrc is now a small untracked file that sources the tracked one. The
# appends land here, *after* everything in .zshrc.shared, which means they can
# still override it — the behaviour an installer was trying to get — while the
# repo stays clean. It also turns the whole "never append to an rc file" class
# of trap from a thing to defend against into a thing that no longer matters.
#
# Re-running must not destroy those appends, so the file is written once and
# thereafter only checked for the source line.

target="$HOME/.zshrc"
shared="$HOME/.zshrc.shared"
backup="$HOME/.dotfiles-backup"

[ -e "$shared" ] || die "no ~/.zshrc.shared — run ./install.sh symlinks first"

# Already ours: leave it exactly as it is, appends and all.
if [ -f "$target" ] && [ ! -L "$target" ] && grep -q '\.zshrc\.shared' "$target"; then
  ok "already a stub sourcing ~/.zshrc.shared (left untouched)"
  info "anything other tools appended to it is preserved"
  return 0
fi

# A symlink into the repo is the old layout; anything else is someone else's
# file. Either way it is moved, never deleted.
if [ -e "$target" ] || [ -L "$target" ]; then
  mkdir -p "$backup"
  mv "$target" "$backup/.zshrc"
  if [ -L "$backup/.zshrc" ]; then
    warn "migrated: the old ~/.zshrc symlink moved to ~/.dotfiles-backup/"
  else
    warn "your old ~/.zshrc moved to ~/.dotfiles-backup/ — check it for local edits"
  fi
fi

# Nothing above the source line may print or read: .zshrc.shared opens with
# p10k's instant prompt, and that has to stay first.
cat >"$target" <<'STUB'
# ~/.zshrc — generated by install.sh, and deliberately NOT tracked.
#
# The real configuration is ~/.zshrc.shared, symlinked from the dotfiles repo.
# This file exists so that installers which append to ~/.zshrc write here
# instead of into the repo. Appended lines run after everything shared, so they
# win — which is what an installer wanted anyway.
#
# Machine-local settings and secrets belong in ~/.zshrc.local, which
# .zshrc.shared sources at its end. Edit the shared config with `zshc`.
[[ -f ~/.zshrc.shared ]] && source ~/.zshrc.shared
STUB

ok "~/.zshrc now sources ~/.zshrc.shared"
