# name: Git config
#
# The portable half of the git config is tracked as config/shared/.gitconfig and
# symlinked by step 10. This step writes the half that cannot be: the path to
# 1Password's SSH signing binary, which lives somewhere different on every OS.
#
# It goes in ~/.config/git/config, which git reads in addition to ~/.gitconfig
# (before it, so the tracked file wins any clash). An [include] in the tracked
# file cannot work: git resolves a relative include against the including
# file's directory — this repo, via the symlink — and does not expand ~/ there.

has git || die "git is missing"

signer=""
case $OS in
  macos) signer="/Applications/1Password.app/Contents/MacOS/op-ssh-sign" ;;
  linux) signer="/opt/1Password/op-ssh-sign" ;;
esac

if [ -n "$signer" ] && [ -x "$signer" ]; then
  mkdir -p "$HOME/.config/git"
  cat >"$HOME/.config/git/config" <<LOCAL
# Generated by ./install.sh — machine-specific, not tracked, edits are lost.
# Read by git in addition to ~/.gitconfig, which is the tracked one.
[gpg "ssh"]
	program = "$signer"
LOCAL
  ok "signing via $(basename "$signer")"
else
  mkdir -p "$HOME/.config/git"
  : >"$HOME/.config/git/config"
  warn "1Password's op-ssh-sign not found — commit signing will fail here"
  info "commit.gpgsign is on in the tracked config; unset it locally if you do not want signing"
fi

name=$(git config --get user.name 2>/dev/null || true)
if [ -n "$name" ]; then
  ok "$name <$(git config --get user.email)>"
else
  warn "no git identity — is ~/.gitconfig linked? run ./install.sh symlinks"
fi
