# name: Git config
#
# Two files, and which one is which is the whole design:
#
#   ~/.config/git/shared.gitconfig   tracked, symlinked, identical everywhere
#   ~/.gitconfig                     generated here, untracked, this machine's
#
# ~/.gitconfig is a real file whose first lines are an [include] of the shared
# one. That single change fixes the oldest problem in this repo: ~/.gitconfig
# used to be a *symlink* into the checkout, so every `git config --global`,
# every `gh auth setup-git`, every tool that set a credential helper, edited a
# tracked file and left the repo dirty. Now those writes land in the untracked
# file — verified: with both files present, git writes to ~/.gitconfig.
#
# The include goes at the top because git takes the last value it reads, so
# anything below it — machine facts, and whatever `git config --global` adds
# later — overrides the shared config without touching the repo.
#
# `[include] path = ~/…` does expand the tilde. This repo used to assert the
# opposite, from a test using `git config --global --list`, which does not
# traverse includes and therefore reports included values as absent. Read a key
# normally, or with --show-origin, and the include is plainly there.

has git || die "git is missing"

shared="$HOME/.config/git/shared.gitconfig"
local_cfg="$HOME/.gitconfig"
backup="$HOME/.dotfiles-backup"

[ -e "$shared" ] || die "no ~/.config/git/shared.gitconfig — run ./install.sh symlinks first"

# Migration, old layout 1: ~/.gitconfig was a symlink into the repo.
if [ -L "$local_cfg" ]; then
  mkdir -p "$backup"
  mv "$local_cfg" "$backup/.gitconfig"
  warn "migrated: the old ~/.gitconfig symlink moved to ~/.dotfiles-backup/"
fi

# Migration, old layout 2: this step used to write the 1Password signer path to
# ~/.config/git/config. Git reads that file *before* ~/.gitconfig, so a leftover
# copy would keep forcing op-ssh-sign — and quietly win over everything set
# below. Retire it, but only if it is one of ours.
old="$HOME/.config/git/config"
if [ -f "$old" ] && grep -q 'Generated by ./install.sh' "$old"; then
  mkdir -p "$backup/.config/git"
  mv "$old" "$backup/.config/git/config"
  warn "retired the old generated ~/.config/git/config (moved to ~/.dotfiles-backup/)"
fi

if [ ! -f "$local_cfg" ]; then
  cat >"$local_cfg" <<'LOCAL'
# ~/.gitconfig — generated by install.sh. This file is NOT tracked.
#
# The include below pulls in the tracked config. Keep it first: git takes the
# last value it reads, so anything after it overrides the shared settings, and
# that is what makes this machine's signing key and any `git config --global`
# you run from here win without editing the dotfiles repo.
#
# Safe to edit and safe to add to. install.sh will not rewrite it; it only
# checks that the include is still present.
[include]
	path = ~/.config/git/shared.gitconfig
LOCAL
  ok "created ~/.gitconfig, including the shared config"
elif grep -q 'shared\.gitconfig' "$local_cfg"; then
  ok "~/.gitconfig already includes the shared config"
else
  # Someone else's ~/.gitconfig, or one from before this step existed. Keep
  # every line of it and put the include first, so their values still win.
  tmp=$(mktemp)
  {
    printf '%s\n' '# Include added by install.sh — the tracked dotfiles config.' \
                  '# Values below this line override it.' \
                  '[include]' '	path = ~/.config/git/shared.gitconfig' ''
    cat "$local_cfg"
  } >"$tmp"
  mv "$tmp" "$local_cfg"
  ok "added the shared include to your existing ~/.gitconfig"
fi

# Prove the include resolved rather than assuming it: user.name lives only in
# the shared file, so reading it back exercises the whole chain.
name=$(git config --get user.name 2>/dev/null || true)
if [ -n "$name" ]; then
  ok "$name <$(git config --get user.email)>"
else
  warn "the shared include is not resolving — check ~/.gitconfig by hand"
fi
