# name: tmux at login
#
# Brings the tmux server up at login so the sessions saved by continuum are
# already restored before you open a terminal. `t` then attaches instantly
# instead of spending a second rebuilding them.
#
# continuum ships its own @continuum-boot for this and it is deliberately not
# used: on macOS it drives AppleScript that opens Terminal.app (or iTerm2, but
# only via a profile that must be named "Tmux"), resizes the window to fill the
# desktop, and types a bare `tmux` — which starts a session *beside* the
# restored ones, the exact thing `t` exists to avoid. It also needs Automation
# permission. This does the one useful part of that and nothing else: no window,
# no AppleScript, no permission prompt.
#
# Both files below are generated, not symlinked — the same split as
# ~/.config/git/config in step 40. The plist has to name an absolute path, and
# the script has to hardcode a PATH, so neither can be portable.

[ "$OS" = macos ] || { info "launchd is macOS-only, skipping"; return 0; }

label="com.jakallergis.tmux"
script="$HOME/.local/bin/dotfiles-tmux-boot"
plist="$HOME/Library/LaunchAgents/$label.plist"

mkdir -p "$HOME/.local/bin" "$HOME/Library/LaunchAgents"

# launchd gives a job /usr/bin:/bin:/usr/sbin:/sbin and nothing else, so tmux
# has to be found by hand. mise keeps a `latest` symlink pointing at whichever
# version is installed, which survives upgrades.
cat >"$script" <<'BOOT'
#!/bin/sh
# Generated by ./install.sh — edits are lost. See steps/macos/36-tmux-boot.sh.
PATH="$HOME/.local/share/mise/installs/tmux/latest:$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
export PATH
command -v tmux >/dev/null 2>&1 || exit 0

tmux has-session 2>/dev/null && exit 0                      # already up
[ -e "$HOME/.local/share/tmux/resurrect/last" ] || exit 0   # nothing saved yet

# Starting a server is what triggers continuum's restore, but a server with no
# sessions exits at once, so the restore needs one to land beside. Placeholder
# is __restore and not `main`, because the saved state usually contains a `main`
# and we would then kill the restored one instead.
tmux new-session -d -s __restore
i=0
while [ "$i" -lt 24 ]; do
  [ "$(tmux list-sessions 2>/dev/null | wc -l)" -gt 1 ] && break
  sleep 0.25
  i=$((i + 1))
done
[ "$(tmux list-sessions 2>/dev/null | wc -l)" -gt 1 ] && tmux kill-session -t '=__restore'
exit 0
BOOT
chmod +x "$script"
ok "$(basename "$script")"

cat >"$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$label</string>
    <key>ProgramArguments</key>
    <array>
        <string>$script</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
PLIST

plutil -lint "$plist" >/dev/null || die "generated plist is malformed"

# bootout first so a re-run reloads rather than erroring with "already loaded".
# Both calls are allowed to fail: bootout on a job that is not loaded returns
# non-zero, and that is not an error here.
launchctl bootout "gui/$(id -u)/$label" 2>/dev/null || true
if launchctl bootstrap "gui/$(id -u)" "$plist" 2>/dev/null; then
  ok "loaded $label"
else
  launchctl load -w "$plist" 2>/dev/null && ok "loaded $label (legacy launchctl)" \
    || warn "could not load $label — it will still start at your next login"
fi

info "disable with: launchctl bootout gui/\$(id -u)/$label && rm $plist"
